sudo: required

services:
  - docker

before_install:
  - travis_wait docker pull viyadb/devenv:latest

jobs:
  include:
    - stage: pre build
      name: check formatting style
      script:
        - docker run --rm -v $(pwd):/viyadb -w /viyadb viyadb/devenv:latest /viyadb/scripts/check-formatting.sh

    - stage: build and test
      name: debug build and test with coverage
      script:
        - docker run --rm -v $(pwd):/viyadb -w /viyadb viyadb/devenv:latest /viyadb/scripts/debug-build.sh
    - name: release build and test
      script:
        - docker run --rm -v $(pwd):/viyadb -w /viyadb viyadb/devenv:latest /viyadb/scripts/release-build.sh

    - stage: after build
      name: publish coverage
      script:
        - bash <(curl -s https://codecov.io/bash) -f $(pwd)/debug/total.info
